# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b5b1a58f6dd413d72deb258ad97396cb"
name = "image-block"
handle = "image-block"
application_url = "https://becoming-scripting-root-economy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "extension-learning.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://becoming-scripting-root-economy.trycloudflare.com/auth/callback",
  "https://becoming-scripting-root-economy.trycloudflare.com/auth/shopify/callback",
  "https://becoming-scripting-root-economy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
